name: 'Wait For Check'
description: 'Wait for another GitHub check to complete'
author: 'Fountainhead Technologies Ltd.'
branding:
  icon: 'check-circle'
  color: 'green'
inputs:
  token:
    description: 'The GitHub token to use for making API requests.'
    required: true
    default: ${{ github.token }}
  checkName:
    description: 'The name of the GitHub check to wait for. For example, `build` or `deploy`.'
    required: true
  ref:
    description: 'The Git ref of the commit you want to poll for a passing check.'
    required: true
    default: ${{ github.event.pull_request.head.sha || github.sha }}
  repo:
    description: 'The name of the GitHub repository you want to poll for a passing check.'
    required: false
  owner:
    description: 'The owner of the GitHub repository you want to poll for a passing check.'
    required: false
  timeoutSeconds:
    description: 'The number of seconds to wait for the check to complete.'
    required: false
  intervalSeconds:
    description: 'The number of seconds to wait before each poll of the GitHub API.'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
